spring:
  datasource:
    url: jdbc:mysql://localhost:3307/clouddb
    username: clouduser
    password: secret

  data:
    redis:
      host: localhost
      port: 6379

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    show-sql: true

  flyway:
    baselineOnMigrate: true
    locations: classpath:db/migration

minio:
  url: http://localhost:9001
  bucket: cloud-storage
  access-key: minioadmin
  secret-key: minioadmin
  port: 9000

url:
  schema: http
  host: localhost
  port: 8080