services:
  db:
    image: 'mysql:latest'
    environment:
      MYSQL_DATABASE: clouddb
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: verysecret
      MYSQL_USER: clouduser
    ports:
      - '3307:3306'

  minio:
    image: minio/minio:latest
    command: server /data/
    volumes:
      - ~/data/minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}

  redis:
    container_name: redis
    image: redis:latest
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - ~/data/redis:/var/lib/redis
      - ~/data/redis/config:/usr/local/etc/redis/redis.conf
